name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main # Execute on push on main branch
  workflow_dispatch: # Allows to execute manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Generate GitHub Stats
      uses: anmol098/waka-readme-stats@master
      with:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Commit and push changes
      run: |
        git config user.name "ChristianRTD"
        git config user.email "crtapia@uce.edu.ec"
        git add .
        git commit -m "Updated GitHub stats in README"
        git push
